"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import classroom from "@/public/classroom.png";
import pyqs from "@/public/pyqs.png";
import quiz from "@/public/quiz.png";
import syllabusm from "@/public/syllabusm.png";
import teacher from "@/public/teacher.png";

export default function Home() {
  const [open, setOpen] = useState(false);

  const features = [
    {
      icon: "🎓",
      title: "AI-Powered Learning",
      description: "Personalized educational content generated by advanced AI algorithms",
      color: "from-blue-500 to-purple-600"
    },
    {
      icon: "📚",
      title: "Smart Materials",
      description: "Automatically generated study materials, quizzes, and practice tests",
      color: "from-green-500 to-teal-600"
    },
    {
      icon: "👥",
      title: "Teacher-Student Bridge",
      description: "Seamless collaboration between educators and learners",
      color: "from-orange-500 to-red-600"
    },
    {
      icon: "📊",
      title: "Analytics & Insights",
      description: "Track progress and optimize learning strategies",
      color: "from-purple-500 to-pink-600"
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-md border-b border-gray-200 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex justify-between items-center">
            <div className="flex items-center space-x-2">
              <div className="w-8 h-8 bg-gradient-to-r from-purple-600 to-blue-600 rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-sm">P</span>
              </div>
              <h1 className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
                ProLearn AI
              </h1>
            </div>
            <nav className="flex items-center gap-8">
              <Link href="/aboutus" className="text-gray-600 hover:text-purple-600 transition-colors font-medium">
                About Us
              </Link>
              <div className="relative">
                <button
                  onClick={() => setOpen(!open)}
                  className="px-6 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-full hover:shadow-lg transition-all duration-200 font-medium"
                >
                  Get Started
                </button>
                {open && (
                  <div className="absolute right-0 mt-2 w-48 bg-white shadow-xl rounded-xl overflow-hidden border border-gray-100">
                    <Link
                      href="/login/student"
                      className="block px-6 py-3 hover:bg-gray-50 transition-colors font-medium text-gray-700"
                    >
                      🎓 Student Login
                    </Link>
                    <Link
                      href="/login/teacher"
                      className="block px-6 py-3 hover:bg-gray-50 transition-colors font-medium text-gray-700"
                    >
                      👨‍🏫 Teacher Login
                    </Link>
                  </div>
                )}
              </div>
            </nav>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-6 py-20">
          <div className="text-center mb-16">
            <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
              Transform Education with
              <span className="block bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
                AI-Powered Learning
              </span>
            </h1>
            <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto leading-relaxed">
              ProLearn AI bridges the gap between teaching and learning through intelligent content generation, 
              personalized materials, and seamless collaboration tools.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/login/student"
                className="px-8 py-4 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-full text-lg font-semibold hover:shadow-xl transition-all duration-200"
              >
                Start Learning
              </Link>
              <Link
                href="/login/teacher"
                className="px-8 py-4 border-2 border-purple-600 text-purple-600 rounded-full text-lg font-semibold hover:bg-purple-600 hover:text-white transition-all duration-200"
              >
                Teach with AI
              </Link>
            </div>
          </div>

          {/* Hero Image */}
          <div className="relative max-w-4xl mx-auto">
            <div className="relative rounded-2xl overflow-hidden shadow-2xl">
              <Image 
                src={classroom} 
                alt="Modern Classroom" 
                className="w-full h-auto"
                priority
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent"></div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Why Choose ProLearn AI?
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Experience the future of education with our cutting-edge AI technology
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div
                key={index}
                className="group p-8 rounded-2xl bg-gradient-to-br from-white to-gray-50 border border-gray-100 hover:shadow-xl transition-all duration-300 hover:-translate-y-2"
              >
                <div className={`w-16 h-16 rounded-2xl bg-gradient-to-r ${feature.color} flex items-center justify-center text-2xl mb-6 group-hover:scale-110 transition-transform duration-300`}>
                  {feature.icon}
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-20 bg-gradient-to-br from-purple-50 to-blue-50">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              How It Works
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Simple steps to revolutionize your learning experience
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center group">
              <div className="w-20 h-20 bg-gradient-to-r from-purple-600 to-blue-600 rounded-full flex items-center justify-center text-white text-2xl font-bold mx-auto mb-6 group-hover:scale-110 transition-transform duration-300">
                1
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-3">Upload Content</h3>
              <p className="text-gray-600">
                Teachers upload course materials, and students provide feedback on their learning experience.
              </p>
            </div>
            <div className="text-center group">
              <div className="w-20 h-20 bg-gradient-to-r from-purple-600 to-blue-600 rounded-full flex items-center justify-center text-white text-2xl font-bold mx-auto mb-6 group-hover:scale-110 transition-transform duration-300">
                2
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-3">AI Processing</h3>
              <p className="text-gray-600">
                Our AI analyzes the content and feedback to generate personalized learning materials and quizzes.
              </p>
            </div>
            <div className="text-center group">
              <div className="w-20 h-20 bg-gradient-to-r from-purple-600 to-blue-600 rounded-full flex items-center justify-center text-white text-2xl font-bold mx-auto mb-6 group-hover:scale-110 transition-transform duration-300">
                3
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-3">Enhanced Learning</h3>
              <p className="text-gray-600">
                Students access tailored content while teachers get insights to improve their teaching methods.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-purple-600 to-blue-600">
        <div className="max-w-4xl mx-auto text-center px-6">
          <h2 className="text-4xl font-bold text-white mb-6">
            Ready to Transform Your Learning?
          </h2>
          <p className="text-xl text-purple-100 mb-8">
            Join thousands of students and teachers already using ProLearn AI
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/login/student"
              className="px-8 py-4 bg-white text-purple-600 rounded-full text-lg font-semibold hover:shadow-xl transition-all duration-200"
            >
              Start as Student
            </Link>
            <Link
              href="/login/teacher"
              className="px-8 py-4 border-2 border-white text-white rounded-full text-lg font-semibold hover:bg-white hover:text-purple-600 transition-all duration-200"
            >
              Start as Teacher
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white">
        <div className="max-w-7xl mx-auto px-6 py-12">
          <div className="grid md:grid-cols-4 gap-8">
            <div className="md:col-span-2">
              <div className="flex items-center space-x-2 mb-4">
                <div className="w-8 h-8 bg-gradient-to-r from-purple-600 to-blue-600 rounded-lg flex items-center justify-center">
                  <span className="text-white font-bold text-sm">P</span>
                </div>
                <h3 className="text-2xl font-bold">ProLearn AI</h3>
              </div>
              <p className="text-gray-400 mb-4 max-w-md">
                Revolutionizing education through AI-powered personalized learning experiences. 
                Bridging the gap between teaching and learning for a smarter future.
              </p>
              <p className="text-sm text-gray-500">
                © 2024 ProLearn AI. All rights reserved.
              </p>
            </div>
            <div>
              <h4 className="text-lg font-semibold mb-4">Quick Links</h4>
              <ul className="space-y-2">
                <li><Link href="/aboutus" className="text-gray-400 hover:text-white transition-colors">About Us</Link></li>
                <li><Link href="/login/student" className="text-gray-400 hover:text-white transition-colors">Student Login</Link></li>
                <li><Link href="/login/teacher" className="text-gray-400 hover:text-white transition-colors">Teacher Login</Link></li>
                <li><Link href="/dashboard" className="text-gray-400 hover:text-white transition-colors">Dashboard</Link></li>
              </ul>
            </div>
            <div>
              <h4 className="text-lg font-semibold mb-4">Contact</h4>
              <div className="space-y-2 text-gray-400">
                <p>📞 +91 9589375565</p>
                <p>✉️ harshitak232@gmail.com</p>
                <p>🌐 www.prolearnai.com</p>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}

